/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant {
    private String name="";
    private float numOfStars=0;
    private double price=0;
    private ArrayList<Review> reviews= new ArrayList<>();

    public Restaurant(String name, double price) {
        this.name = name;
        this.price= price;
    }



    public String getName() {
        return name;
    }

    public double getPrice() {
        return price;
    }

    public float getNumOfStars() {
        return numOfStars;
    }

    public ArrayList<Review> getReviews() {
        return reviews;
    }

    public void addReview(Review review){
        reviews.add(review);

        int sum=0;
        for (Review rev: reviews){
            sum= (int) (rev.getNumOfStars() + sum);
        }
        numOfStars= (float) sum/reviews.size();
        System.out.println("num of stars:" + numOfStars);

    }

    @Override
    public String toString() {
        return "Restaurant{" + "name='" + name + '\'' + ", numOfStars=" + numOfStars + ", price=" + price + "$ " + reviews +'}';
    }

}
